apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  Name: sample15
spec:
  ttlStrategy:
    secondsAfterCompletion: 60
    secondsAfterSuccess: 60
    secondsAfterFailure: 60
  entrypoint: main
  templates: 
  - name: main
    steps:
      - - name: random-fail
          template: random-fail
          continueOn:
            failed: true
      - - name: after-succeeded
          when: "{{steps.random-fail.status}} == Succeeded"
          template: whalesay
          arguments:
            parameters:
              - name: message
                value: "success!"
        - name: after-failed
          when: "{{steps.random-fail.status}} == Failed"
          template: whalesay
          arguments:
            parameters:
              - name: message
                value: "fail!"
  - name: random-fail
    script:
      image: python:alpine3.6
      command: ["python"]
      source: |
        import random
        import sys
        exit_code = random.choice([0, 1])
        sys.exit(exit_code)
  - name: whalesay
    inputs:
      parameters:
        - name: message
          value: default
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
