# artifact を configMap で設定する
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
data:
  minio-artifact: |
    s3:
      bucket: my-bucket
      endpoint: argo-artifacts:9000
      insecure: true
      accessKeySecret:
        name: argo-artifacts
        key: accesskey
      secretKeySecret:
        name: argo-artifacts
        key: secretkey
spec:
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: minio-artifact
  entrypoint: main
  templates: 
  - name: main
    steps:
      - - name: generate-artifact
          template: whalesay
      - - name: consume-artifact
          template: print-message
          arguments:
            artifacts:
            - name: message
              from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello | tee /mnt/vol/hello_world.txt"]
      outputs:
        artifacts:
        - name: hello-art
          path: /tmp/hello_world.txt
  - name: print-message
    serviceAccountName: workflow-sa
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
      input:
        artifacts:
        - name: message
          path: /tmp/message