apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  Name: sample19
spec:
  ttlStrategy:
    secondsAfterCompletion: 60
    secondsAfterSuccess: 60
    secondsAfterFailure: 60
  entrypoint: main
  templates: 
  - name: main
    steps:
      - - name: hello
          template: whalesay
      - - name: need-approve
          template: need-approve
      - - name: after-approve
          template: whalesay
  - name: need-approve
    suspend: {}
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hogehoge"]
