apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  Name: sample1
spec:
  entrypoint: main
  templates: 
  - name: main
    steps:
      - - name: step1
          template: whalesay
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["step1"]
