apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  Name: sample28
  labels:
    message-from-labels: hoge
spec:
  ttlStrategy:
    secondsAfterCompletion: 60
    secondsAfterSuccess: 60
    secondsAfterFailure: 60
  entrypoint: main
  templates: 
  - name: main
    steps:
      - - name: whalesay
          template: whalesay
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{workflow.labels.message-from-labels}}"]
