apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  Name: sample22
spec:
  ttlStrategy:
    secondsAfterCompletion: 60
    secondsAfterSuccess: 60
    secondsAfterFailure: 60
  entrypoint: main
  templates: 
  - name: main
    steps:
      - - name: place-kubectl
          template: place-kubectl
  - name: place-kubectl
    inputs:
      artifacts: 
      - name: kubectl
        path: /usr/local/bin/kubectl
        mode: 0755
        http:
          url: https://storage.googleapis.com/kubernetes-release/release/v1.22.2/bin/linux/amd64/kubectl
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["/usr/local/bin/kubectl version --client"]
